# Generated by Django 5.2.1 on 2025-06-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_created_at_follow_timestamp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
