# Generated by Django 5.2.1 on 2025-06-13 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='is_accepted',
        ),
    ]
