# Generated by Django 5.2.1 on 2025-06-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
