# Generated by Django 5.2.1 on 2025-06-29 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_message_read_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read_at',
        ),
    ]
