# Generated by Django 5.2.1 on 2025-06-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_message_deleted_for_message_deleted_globally'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='deleted_globally',
            new_name='deleted_for_everyone',
        ),
    ]
