# Generated by Django 5.2.1 on 2025-07-05 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_message_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='audio_file',
        ),
    ]
